### ISSUE TITLE
 [Merch] Change Cursor to Pointer when selecting different image thumbnail

### ISSUE THREAD

**Issue by zakuArbor** [cumathsoc/cumathsoc.github.io#9]
**Task:** When a user is hovering around the thumbnail image, have the cursor change to a pointer. This is to make the UX more intuitive that the image is selectable.

Look at: https://www.w3schools.com/cssref/pr_class_cursor.php

**Comment by karthickbharathi1** [comment]
Hey @zakuArbor , I would like to contribute can you assign me?
